### ISSUE TITLE
Make lint more robust in cloudflare and autogen workspaces

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1073]
In #1023 we have enabled clippy for all workspaces

In order to make it pass on CI we have allowed few rules in some files

1. `#[allow(clippy::same_item_push)]` and `#[allow(clippy::too_many_arguments)]` in `autogen/src/gen_gql_schema.rs`
1. `#[allow(clippy::arc_with_non_send_sync)]` in `cloudflare/src/lib.rs`

Refactor the functions so that we don't need to allow these lint warnings.

**Comment by emadbaqeri** [comment]
Hey @amitksingh1490, is there any specific reason for lowering the `too-many-arguments-threshold` from the default of 7 to 4. If we choose to go with the default config we can eliminate all the `clippy::to_many_arguments`. As I've gone through the code base I saw we do have maximum of 6 arguments for the functions.

**Comment by emadbaqeri** [comment]
Another thing is for the `clippy::mutable_key_type`, I haven't touched anything yet but if I do this I have to change most of the types too. For example wrapping types into `Arc<T>` or `Rc<T>` I would probably leave this as is, because I don't have much experience dealing with these kind of things or maybe I should or maybe I don't have the confidence for changing lots of code and implementing `Clone` trait for some types alongside `Copy` and etc.

**Comment by varshith257** [comment]
@tusharmath  Is this issue ready to work?

**Comment by varshith257** [comment]
!stalebot reopen
