### ISSUE TITLE
Better Json Support for ValidationError

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1105]
Currently ValidationError are designed to look pretty on the console but not for the web.
Here is a sample validation error:

```json
{
  "status": 200,
  "headers": {
    "content-type": "application/json"
  },
  "body": {
    "data": null,
    "errors": [
      {
        "message": "Failed to read config: Validation Error\n•  --> 1:1\n  |\n1 | \"dsjfsjdfjdsfjkdskjfjkds\"\n  | ^---\n  |\n  = expected type_system_definition\n"
      }
    ]
  }
}
```

**Proposal**
Add first class support for JSON in ValidationError. This can be achieved by implementing Serialize, Deserialize for ValidationError.

**Comment by mogery** [comment]
I can get on this. @tusharmath

**Comment by deepam-kapur** [comment]
oh sorry I missed that! Let me know if I can help or work on this.

**Comment by mogery** [comment]
> oh sorry I missed that! Let me know if I can help or work on this.

no worries! i might have a bit too high of a workload to drive this issue. i'll let you know in that case

**Comment by mogery** [comment]
Unfortunately, after spending a lot of time untangling the error structure (implementing `Serialize` for `ValidationError` was not enough, as `anyhow::Error` blocks everything), I've determined that first-class JSON support, at least for syntax errors, is impossible due to how `async_graphql` handles errors.

When digging down through the layers of various Error enums, this is the lowest you can go:
```
Parse(
    GraphQL(
        Syntax {
            message: " --> 1:1\n  |\n1 | \"dsjfsjdfjdsfjkdskjfjkds\"\n  | ^---\n  |\n  = expected type_system_definition",
            start: Pos(1:1),
            end: None,
        },
    )
)
```

Unforunately, `async_graphql` doesn't let you get at a structured form of the syntax error message, so the error response in JSON will always look ugly. [Reference](https://docs.rs/async-graphql-parser/7.0.1/async_graphql_parser/enum.Error.html)

**Comment by tusharmath** [comment]
@mogery I think we should try to "jsonify" it as deep as possible and bail out when we can't. Currently it bails out too soon.
