### ISSUE TITLE
refactor: Enhance ConfigModule

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1642]
Config is designed to be optimized for writes and not for reads. This makes it expensive to query and find stuff in the config. Let's leverage ConfigModule for it.

**Technical Requirements**
- Implement optimized versions for the following functions in config_module such that they have typically a `O(1)` complexity to lookup.
  - [ ] `output_types`
  - [ ] `input_types`
  - [ ] `find_type`
  - [ ] `find_union`
  - [ ] `contains`
- Drop these methods from `Config`.

**Comment by ologbonowiwi** [comment]
I'd love to /attempt this. Can you assign?

**Comment by atamakahere-git** [comment]
/attempt 

Will take up if @ologbonowiwi drops

**Comment by ologbonowiwi** [comment]
Hey @atamakahere-git, I have a thread discussing this issue with Tushar on Discord and a draft PR open. I don't want to compete for the issue, but I'd appreciate it if you close #1661 since I'm working on this already.

We may not need to use `ConfigModule` at all to accomplish `O(1)` time reading; there are other ways to achieve it.

**Comment by atamakahere-git** [comment]
@ologbonowiwi alright.
I have basically completed what's needed, you can pick anything useful from there if you want.
