### ISSUE TITLE
Resolve Ambiguous Types in Configuration Automatically

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1870]
**Issue Description:**  
Presently, when the same type is used in both the input and output sections of the configuration in our `definitions.rs` file 
https://github.com/tailcallhq/tailcall/blob/dd2114deb7c939d44798b945f8491b1801678125/src/blueprint/definitions.rs#L536.
(ref: [line 536](https://github.com/tailcallhq/tailcall/blob/dd2114deb7c939d44798b945f8491b1801678125/src/blueprint/definitions.rs#L536)), the Tailcall CLI throws an error.

To enhance the user experience we can infer this from the config, we can leverage the existing `resolve_ambiguous_types` function in the `ConfigModule` to automatically resolve this issue.

**Requirements:**  
- [ ] The Tailcall CLI no longer throws errors when the same type is used in both the input and output sections of the configuration.
- [ ] Ambiguous type are automatically detected and resolved using the `resolve_ambiguous_types` function.
- [ ] Integration test for this using `execution_spec` should be added.

**Comment by maks-ivanov** [comment]
Hey! Here's a short impl I came up with:

Here are the complete code edits to implement the automatic resolution of ambiguous types in Tailcall:

### Edit 1: Update to_definitions logic to resolve ambiguous types

**File:** `src/blueprint/definitions.rs`

Description: Replace the `Valid::fail` on line 536 with a call to `resolve_ambiguous_types`. Continue generating the blueprint definition using the resolved types.

Code:

```rust
} else if dbl_usage {
    let resolved_config_module = config_module.resolve_ambiguous_types(|type_name| {
        Resolution { 
            input: format!("{}Input", type_name),
            output: format!("{}Output", type_name),
        }
    });

    to_object_type_definition(name, type_, &resolved_config_module)
        .trace(name) 
        .and_then(|definition| match definition.clone() {
            Definition::Object(object_type_definition) => {
                if resolved_config_module.input_types.contains(name) {
                    to_input_object_type_definition(object_type_definition).trace(name)
                } else if resolved_config_module.interface_types.contains(name) {
                    to_interface_type_definition(object_type_definition).trace(name)
                } else {
                    Valid::succeed(definition)  
                }
            }
            _ => Valid::succeed(definition),
        })
        .map(|definition| {
            // Update references to the original type name
            let type_name = name.to_string();
            match definition {
                Definition::Object(mut obj_def) => {
                    obj_def.name = resolved_config_module.output_types.get(&type_name)
                        .cloned()
                        .unwrap_or(obj_def.name);
                    obj_def.fields.iter_mut().for_each(|field| {
                        update_type_references(&mut field.of_type, &type_name, &resolved_config_module);
                    });
                    Definition::Object(obj_def)
                }
                Definition::InputObject(mut input_def) => {
                    input_def.name = resolved_config_module.input_types.get(&type_name)
                        .cloned() 
                        .unwrap_or(input_def.name);
                    input_def.fields.iter_mut().for_each(|field| {
                        update_type_references(&mut field.of_type, &type_name, &resolved_config_module);
                    });
                    Definition::InputObject(input_def)
                }
                def => def,
            }
        })
```

Add the `update_type_references` helper function:

```rust
fn update_type_references(field_type: &mut Type, type_name: &str, config_module: &ConfigModule) {
    match field_type {
        Type::NamedType { name, .. } if name == type_name => {
            if config_module.output_types.contains(type_name) {
                *name = config_module.output_types.get(type_name).cloned().unwrap_or_else(|| name.clone());
            } else if config_module.input_types.contains(type_name) {
                *name = config_module.input_types.get(type_name).cloned().unwrap_or_else(|| name.clone());
            }
        }
        Type::ListType { of_type, .. } => {
            update_type_references(of_type, type_name, config_module);
        }
        _ => {}
    }
}
```

### Edit 2: Add new execution spec for ambiguous types

**File:** `tests/execution/ambiguous-types.md`

Description: Create a new file with the following contents:

Code:

```markdown
# ambiguous-types

Verify that types used in both input and output are automatically resolved.

    ```graphql
    type Foo {
      id: ID!
      name: String!
    }
    
    input FooInput {
      fooField: Foo!
    }
    
    type Query {
      getFoo(input: FooInput!): Foo!
    }
    ```

    ```graphql
    query {
      getFoo(input: {
        fooField: {
          id: "abc123"
          name: "Test Foo" 
        }
      }) {
        id
        name
      }
    }
    ```
        
|||
        
    ```json
    {
      "data": {
        "getFoo": {
          "id": "abc123",
          "name": "Test Foo"
        }
      }
    }
    ```

```

### Edit 3: Include new execution spec in test harness
**File:** `tests/execution_spec.rs`

Description: Add `ambiguous-types.md` to the glob pattern in the `datatest_stable::harness!` macro.

Code:
```rust
datatest_stable::harness!(run_execution_spec, "tests/execution", r"^(ambiguous-types\.md|.*)$");
```

1. The `to_definitions` logic now resolves ambiguous types using `resolve_ambiguous_types` instead of failing. It generates the blueprint definitions using the resolved input/output type names.

2. References to the original ambiguous type name are updated throughout the generated blueprint definitions to use the new resolved names.

3. A new execution spec `ambiguous-types.md` is added to test that a query using an ambiguous type in both input and output executes successfully after the automatic resolution.

4. The new spec file is included in the `execution_spec.rs` test harness.



I'm by no means an expert, just trying out Glide, the tool I'm building, on some real problems.
This is not an automated post and I'm happy to remove it if it adds noise for the team, but my goal is to help!
If you're curious, here's what it looks like: https://glide.agenticlabs.com/sharing?userId=65bae7547a39e05fc421bd8c&taskId=qWBEVJC

**Comment by tusharmath** [comment]
Thanks @maks-ivanov sorry had to delete your AI Generated comment. It was causing more confusion and wasn't correct. Request you to not comment with AI-generated content in the future.
