### ISSUE TITLE
bug: @expr with template forcibly converts string value to primitive value

### ISSUE THREAD

**Issue by meskill** [tailcallhq/tailcall#2039]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

When using `@expr` with a template like `{{.value.a}}` then generated value is always coerced to primitive value despite the type of the original value.

### Steps to reproduce

The tests in this pr https://github.com/tailcallhq/tailcall/pull/2038/files#diff-acbd705baf4dd912244b9d40a6cd839f3c11d8a30019132e8368a64f947768e1R19-R27 shows the problem in the related snapshots. Despite the type of the value in root Value in nested it always converted to primitive values like int or bool even if you try to add additional quotes like `"\"{{.value.a}}\""`

### Expected behaviour

Type of the value should be preserved in `@expr`

### Actual behaviour

Type is forcibly coerced to primitive value

**Comment by bnchi** [comment]
@meskill 

Seems like mustache is parsing these values correctly the root cause if I'm not mistaken is when _render_value_ is getting invoked here : 

https://github.com/tailcallhq/tailcall/blob/9cdf3ef8b8efcdd5b1c5934a94c6312c7087564e/src/core/serde_value_ext.rs#L20

**Comment by bnchi** [comment]
Hmm well actually mustache is associating the type to a primitive type like so :

```
"0" Mustache([Expression(["value", "num"])])                                                                                                                                                
"[1, 2, 3]" Mustache([Expression(["value", "arr"])])                                                                                                                                    
"test" Mustache([Expression(["value", "str"])])                                             
"{e: 1}" Mustache([Expression(["value", "obj"])])                                                                                                                                       
"true" Mustache([Expression(["value", "bool"])])
```

The value that's being passed to Serde is still str and the root cause must be from there.

My proposed solution would be, if we can check the mustache expression type and if it's a str we can just return something like _GraphQLValue::String(value)_

That will still require fixes on the way of how mustache is associating types seems like.

Let me know what do you think.

**Comment by meskill** [comment]
the mustache parser probably not the issue itself (although, it does strip `"` symbols from input on parsing) but mostly the render. Since Mustache::render is mostly made for using in strings like urls the output is generated without quotes and we try to convert it  back to serde::Value we get the converted value that could be not a string in the first place.

I think it could be solved with the change like was made here https://github.com/tailcallhq/tailcall/pull/1556/files#diff-855a66b57f6600cfd1af0da76b2be55e275d89f3d3fb57cfa03255b1b0aef453 i.e. return `Value` from `Mustache::render` instead of string. But this pr wasn't merged due to performance implications.

**Comment by bnchi** [comment]
> the mustache parser probably not the issue itself (although, it does strip `"` symbols from input on parsing) but mostly the render. Since Mustache::render is mostly made for using in strings like urls the output is generated without quotes and when we try to convert it back to serde::Value we get the converted value that could be a string in the first place.
> 
> I think it could be solved with the change like was made here https://github.com/tailcallhq/tailcall/pull/1556/files#diff-855a66b57f6600cfd1af0da76b2be55e275d89f3d3fb57cfa03255b1b0aef453 i.e. return `Value` from `Mustache::render` instead of string. But this pr wasn't merged due to performance implications.

That's what I concluded too and why I said it's tricky for me because I don't know the codebase well. 
I was thinking about changing the _PathString_ trait and making the _path_string_ return a tuple something like _(type, Cow)_ where the type is the type that got converted and we can match against it inside that block if it was a string simply return _GraphQLValue::String_ otherwise keep the logic as is, but I don't know if that's a solid idea because it require all the implementers of this trait to do the same thing. what are you thoughts ? 

https://github.com/tailcallhq/tailcall/blob/5f54bca8b589c88a257c2f759808c7a3b453e88d/src/core/path.rs#L17

**Comment by meskill** [comment]
seems like the issue could be resolved by this issue https://github.com/tailcallhq/tailcall/issues/1535 and more precisely this part "Optimize serde_value_ext::render_value. It renders itself as a string and then deserializes it as json."

@tusharmath do you have any plans on it?

**Comment by bnchi** [comment]
Just wanted to extend on my idea to make sure it's clear enough, I re-read the the implementers of _PathString_ and if I would to return a tuple from the _path_string_ the type that's going to be returned is simply an _enum_ that looks exactly the same as _serde_json::Value_ and _async_graphql::Value_

Something like :

```rust 
enum TailCallValue {
 String,
 List,
 Object,
 Bool
}
```

it's a cheap one but it could solve this problem(with potentially not a lot of changes)
