### ISSUE TITLE
Support `@modify` on inputs

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2483]
Context Discussion - https://github.com/tailcallhq/tailcall/discussions/2476

The [@modify](https://tailcall.run/docs/tailcall-dsl-graphql-custom-directives/#modify-directive) only works on output types. We need to support `@modify` on input types as well

**Proposal**

```graphql
type Query {
  ask(question: Question): Answer
}

type Answer {
  text: [String]
}

input Question {
  prompt: String
  model: String
  system: String @modify(name: "systemPrompt")
}
```

The generated client schema should look like:

```graphql
type Query {
  ask(question: Question): Answer
}

type Answer {
  text: [String]
}

input Question {
  prompt: String
  model: String
  systemPrompt: String # Field is renamed
}
```

Internally Tailcall should handle these field name conversions efficiently.

**Technical Requirements**
- Ensure both unit and integration tests are added wherever necessary.

**Comment by bnchi** [comment]
The current behavior seem to be correct ?!

Current config

```graphql
schema
  @server(port: 8000)
  @upstream(baseURL: "http://localhost:3000", httpCache: 42, batch: {delay: 100}) {
  query: Query
}

type Query {
  searchUser(input: UserSearch): [User]!
    @http(
      method: POST
      path: "/users/search"
      body: "{{.args.input}}"
    )
}

input UserSearch {
  emailAddress: String! @modify(name: "email_address")
}

type User {
  id: Int!
  name: String!
  email: String!
}
```

The generated client schema for _UserSearch_ from the playground : 
```graphql
Input UserSeach {
 email_address: String!
}```

**Comment by angristan** [comment]
Ok, let me try to make it more clear 🙏  Keep in mind that the issue I'm seeing is that I want to have consistency in the casing of my schema. Having mixed snake case and camel case because of the underlying resolvers is not ideal IMO.

First, `@modify` doesn't seem to be allowed on inputs:

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/2a82396c-c939-4998-90f0-73ffcf3db82e">

But it does kinda work.

## `emailAddress: String! @modify(name: "email_address")`

Example schema:

```gql
schema @server(port: 8000) @upstream(baseURL: "http://localhost:8008") {
  query: Query
}

type Query {
  searchUser(input: UserSearch): [User]!
    @http(method: POST, path: "/users/search", body: "{{.args.input}}")
}

input UserSearch {
  emailAddress: String! @modify(name: "email_address")
}

type User {
  id: Int!
  name: String!
  email: String!
}
```

Example query:

```gql
query test {
  searchUser(input: {email_address: "test@test"}) {
    id
  }
}
```

Running `nc -l 8008` you'll see:

```http
POST /users/search HTTP/1.1
content-type: application/json
accept: */*
user-agent: Tailcall/1.0
host: localhost:8008
content-length: 29

{"email_address":"test@test"}
```

Issue: the `email_address` is forced to be snake case in the exposed schema, which breaks consistency. There is no point in using `@modify` here since the resulting schema is snake case, we could just have:

```gql
input UserSearch {
  email_address: String!
}
```

Which is also snake case :/ 

## `email_address: String! @modify(name: "emailAddress")`

Schema:

```gql
schema @server(port: 8000) @upstream(baseURL: "http://localhost:8008") {
  query: Query
}

type Query {
  searchUser(input: UserSearch): [User]!
    @http(method: POST, path: "/users/search", body: "{{.args.input}}")
}

input UserSearch {
  email_address: String! @modify(name: "emailAddress")
}

type User {
  id: Int!
  name: String!
  email: String!
}
```


Query:
```gql
query test {
  searchUser(input: {emailAddress: "test@test"}) {
    id
  }
}
```

Payload:

```http
POST /users/search HTTP/1.1
content-type: application/json
accept: */*
user-agent: Tailcall/1.0
host: localhost:8008
content-length: 28

{"emailAddress":"test@test"}
```

Here is the issue is the opposite, we do have `emailAddress` in the exposed schema, but it's `emailAddress` that is serialized, not `email_address`.

**Comment by bnchi** [comment]
alright thank you for clarification makes sense now
