### ISSUE TITLE
Batching with nested HTTP responses

### ISSUE THREAD

**Issue by angristan** [tailcallhq/tailcall#2489]
Given this example:

```gql
type Transaction {
  id: ID!
  slug: String!
  bank_account_id: String! 
  BankAccounts: BankAccountResponse @http(
      path: "/v1/bank_accounts"
      query: [{ key: "bank_account_ids[]", value: "{{.value.bank_account_id}}" }]
      batchKey: ["bank_account_ids[]"]
    )
}

type BankAccountResponse {
  bank_accounts: [BankAccount!]!
}

type BankAccount {
  id: ID!
  bic: String!
  iban: String!
}
```

Without batching, this work fine to get the BankAccount information. 

However, with batching, the query is indeed batched but all the `Transactions.BankAccounts` are null.

As discussed on discord, the suggestion was to use `["bank_accounts", "id"]` as the batching key however this doesn't match the query param and the error `Unable to find key id in query params` is returned.

**Comment by angristan** [comment]
Sure, initial payload:

```json
{
    "transactions": [
        {
            "id": "7964963e-06e8-46a7-b228-04fc08fd020f",
            "slug": "slug-tx-1",
            "bank_account_id": "441ff0f9-c00d-45cc-8bbf-5a8fffa01798"
        },
        {
            "id": "140b5e4d-b9c0-40f7-97ec-313c9bda2b00",
            "slug": "slug-tx-2",
            "bank_account_id": "ea2efff5-6d7c-4cf3-bada-8447e139a864"
        }
    ],
    "meta": {
        "current_page": 1,
        "next_page": 2,
        "prev_page": null,
        "total_pages": 2,
        "total_count": 4,
        "per_page": 2
    }
}
```

Then querying `/v1/bank_accounts?bank_account_ids[]=441ff0f9-c00d-45cc-8bbf-5a8fffa01798&bank_account_ids[]=ea2efff5-6d7c-4cf3-bada-8447e139a864`:

```json
{
  "bank_accounts": [
    {
      "id": "441ff0f9-c00d-45cc-8bbf-5a8fffa01798",
      "iban": "iban1",
      "bic": "bic1"
    },
    {
      "id": "ea2efff5-6d7c-4cf3-bada-8447e139a864",
      "iban": "iban2",
      "bic": "bic2"
    }
  ],
  "meta": {
    "current_page": 1,
    "next_page": 2,
    "prev_page": null,
    "total_pages": 2,
    "total_count": 4,
    "per_page": 2
  }
}
```

Does that help?

**Comment by angristan** [comment]
> @angristan can you try schema in following way? this will ignore that meta property and will give you direct access to bank account.

As mentioned in the original post, I get `Unable to find key id in query params` with `batchKey: ["bank_accounts", "id"]` 🤔

**Comment by tusharmath** [comment]
@dekkku you might want to look at the groupBy ir. I think it isn't working correctly.

**Comment by karatakis** [comment]
@dekkku I did some debugging, and I found the following:

Given the payloads @angristan provided, Tailcall requests the following URL

`/v1/bank_accounts?bank_account_ids[]=441ff0f9-00d-45cc-8bbf-5a8fffa01798&bank_account_ids%5B%5D=ea2efff5-6d7c-4cf3-bada-8447e139a864`

In the code below (src/core/http/data_loader.rs)
```rust
[...]
let pairs: Vec<_> = url
  .query_pairs()
  .filter(|(key, _)| group_by.path().contains(&key.to_string()))
  .collect();
[...]
```

I noticed that the result from `url.query_pairs()` is `HashMap { "bank_account_ids[]": "ea2efff5-6d7c-4cf3-bada-8447e139a864" }`

Resulting in `pairs = Vec [("bank_account_ids[]", "ea2efff5-6d7c-4cf3-bada-8447e139a864")]`

Ideally, it would have been `Vec [("bank_account_ids[]", "441ff0f9-00d-45cc-8bbf-5a8fffa01798"), ("bank_account_ids[]", "ea2efff5-6d7c-4cf3-bada-8447e139a864")]`

@tusharmath I am curious to know if the current behavior is correct (it looks like a bug), but I will dig deeper to understand how it works.

**Comment by karatakis** [comment]
I noticed that the problem is that the query expects `bank_account_ids[]` while the object returned by the API groupBy key is `id`

### Draft Solution
Use the following enum in the `batchKey` field.

```rust
pub struct GroupBy {
    #[serde(default, skip_serializing_if = "is_default")]
    path: Vec<GroupByEnum>,
}

pub enum GroupByEnum {
    #[serde(rename = "query")]
    Query(String),
    #[serde(rename = "rename")]
    Rename { query: String, object: String },
}
```
So, we drive Tailcall using the following configuration:

```graphql
type Transaction {
  id: ID!
  slug: String!
  bank_account_id: String!
  BankAccounts: [BankAccount!]!
    @http(
      path: "/v1/bank_accounts"
      query: [{key: "bank_account_ids[]", value: "{{.value.bank_account_id}}"}]
      batchKey: [{ query: "bank_account_ids[]", object: "id" }] 
    )
}

# It is backward-compatible
type OtherType {
 id: ID!
 user_id: String!
 Users: [User!]!
    @http(
      path: "/v1/users"
      query: [{key: "id[]", value: "{{.value.user_id}}"}]
      batchKey: ["id"] 
    )
```

**Advantages / Disadvantages**
- (Adv) Backwards compatible
- (Adv) Check correctness of configuration on parsing
- (Dis) Requires a small part of the parser to be custom (because default serde requires `[{rename: {query: "query_id", target: "terget_id"}, query: "id"]`
- (Dis) Complex implementation

### Draft solution alternative
Use `:` (example: `bank_account_ids[]:id` as a delimiter to separate the `query` and `target` parts, but it only solves our problem temporarily (in the long term, someone might want to use `user::id` as a query parameter, and we will have trouble again.

@tusharmath, what are your thoughts?

**Comment by bnchi** [comment]
@karatakis On the top of my head for your draft solution a single object won't be enough : 
  
`batchKey: [{ query: "bank_account_ids[]", object: "id" }] `

object needs to be an array ["id", "bank_accounts"] due to the logic here: 

https://github.com/tailcallhq/tailcall/blob/f40ad41e7e17ef13977d08b9a0f373939fdc6e21/src/core/json/mod.rs#L14

Which is called from : 
https://github.com/tailcallhq/tailcall/blob/f40ad41e7e17ef13977d08b9a0f373939fdc6e21/src/core/json/graphql.rs#L97

From the example given in the issue, it needs to match _bank_account_ as a key and then _id_

**Comment by karatakis** [comment]
I made a solution https://github.com/tailcallhq/tailcall/pull/2495

Another alternative for a more structured config is to convert `GroupByEnum` to a struct

```rust
struct GroupByConfig {
  query: String,
  rename: Option<String>,
}
```

**Comment by tusharmath** [comment]
Fixed in https://github.com/tailcallhq/tailcall/releases/tag/v0.97.0
