### ISSUE TITLE
Add a `--watch` feature

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2688]
Use `rs-notify` library to identify if the source files have changed and restart the server when it does. 

**Example Usage**
```bash
tailcall start ./jp.graphql --watch
```

**Technical Requirements**
- Restart should happen automatically when the main config or any of the linked file changes.
- There should be no leaks in restarts and should happen seamlessly.
- Should not crash the server if there is a validation error.

**Comment by bnchi** [comment]
rs-notify doesn't work well with VIM or some other editors when watching for specific files : https://docs.rs/notify/latest/notify/#editor-behaviour

It's also a bit tricky as well to watch for files that are linked in a _@link_ directive because the src path is relative to the file they're defined in

**Comment by beelchester** [comment]
> rs-notify doesn't work well with VIM or some other editors when watching for specific files : https://docs.rs/notify/latest/notify/#editor-behaviour

Yes, true. It may trigger 2 or more data change events on a single file modification.
To fix this I have added a debounce delay in my PR (https://github.com/tailcallhq/tailcall/pull/2707), it ignores modification events for a specified time after the initial trigger to restart the server. It is working reliably well.
