### ISSUE TITLE
Deprecate `@inline` operator

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#598]
List of tasks 

- [ ] Drop inline operator
- [ ] Fix tests which use inline with addField operator

**Comment by Min2who** [comment]
can you assigned this to me @tusharmath

**Comment by ologbonowiwi** [comment]
Hey guys, in this case
```graphql
type Query {
  foo: [Foo] @http(path: "/foo") @inline(path: ["a", "0", "b"])
}
```

when I change it to
```graphql
type Query @addField(name: "foo", path: ["foo", "a", "0", "b"]) {
  foo: [Foo] @http(path: "/foo")
}
```

I'm getting the error `thread 'test_server_to_client_sdl' panicked at 'Field `foo` already exists', src/index.crates.io-6f17d22bba15001f/async-graphql-6.0.10/src/dynamic/object.rs:82:9`

Is this expected? It makes some sense since `addField` essentially adds a new field, while `inline` can also override an existing field. Should we add this behavior of overriding the field type on `addField`?
