### ISSUE TITLE
Upgrade hyper to 1.0

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#650]
Renovate has created the base PR which doesn't pass the CI checks.

https://github.com/tailcallhq/tailcall/pull/636

**Technical Requirements**
- Hyper version for both server should be updated to 1.0
- No performance degradation should be observed
- No tests should fail or require modification

**Comment by ssddOnTop** [comment]
Can you assign this to me

**Comment by ayewo** [comment]
@tusharmath I’ve not got any new tickets in a bit 🙌

**Comment by b4s36t4** [comment]
@tusharmath I request you to assign this to me.

I have done some digging into the issue why the compilation is issue.

I think you should put this to hold because of two reasons.

1. We heavily depend on `hyper` and `reqwest`
2. `hyper` and `reqwest` are co-related here in this context thus `reqwest` also should be updated according to the version of `hyper` due to mis-matching type definitions. 

We should wait till `reqwest` get's same version update that matches with `hypers` latest version (reqwest is going to be breaking change)

more on this https://github.com/seanmonstar/reqwest/issues/2039
<img width="999" alt="Screenshot 2023-11-17 at 11 19 33 PM" src="https://github.com/tailcallhq/tailcall/assets/59088937/8c68ca5d-233a-48d6-93e5-5567e489b4dc">

**Comment by tusharmath** [comment]
Thanks @b4s36t4 .

@ayewo let me keep this unassigned until reqwest also upgrades.

**Comment by ssddOnTop** [comment]
I won't be attempting this issue again..
for anyone who picks this up, you can refer to my previous PRs on how I handled requests (because hyper::Body is a trait now).
