### ISSUE TITLE
Making check subcommand more ci friendly

### ISSUE THREAD

**Issue by alexanderjophus** [tailcallhq/tailcall#699]
**Is your feature request related to a problem? Please describe.**
Currently the check command is very good for locally checking the state of the graphql schema, particularly highlighting where the n+1 problems are.

**Describe the solution you'd like**
I'd like to have a `--threshold <int>` argument that when exceeded returns an exit code != 0. This would allow me to ensure that n+1 problems do not creep into my project.

**Describe alternatives you've considered**
Currently we could grep for it and ensure it's not over the number, but something built into the tool would be preferable.

**Additional context**
In the discord we also discussed potential future steps for this;
- allowlisting certain n+1 calls i.e. `@http(path: "/users/{{value.userId}}")  @check(ignore: ["n+1"])`
- still flagging up the n+1 call in check, but just showing it as allowlisted
```diff
No errors found
-N + 1: 1
+N + 1: 1 (1 whitelisted)
```

**Comment by tusharmath** [comment]
I like this. Instead of whitelisted we could do "Allowed"

```diff
No errors found
-N + 1: 1
+N + 1: 1 (1 allowed)
```

We can allow using the `@allow` directive. 


```diff
  schema @upstream(baseURL: "http://jsonplaceholder.typicode.com") {
    query: Query
  }
  
  type Query {
    posts: [Post] @http(path: "/posts")
  }
  
  type User {
    id: Int!
    name: String!
  }
  
  type Post {
    id: Int!
    userId: Int!
    title: String!
-   user: User @http(path: "/users/{{value.userId}}")
+   user: User @http(path: "/users/{{value.userId}}") @allow(checks: ["n+1"])
  }
```

**Comment by tusharmath** [comment]
On second thoughts this might not work as intended, because n + 1 is not a field level problem but a path problem. We will have to create allowed paths for eg:

```graphql
schema @allow(npo: {query: ["posts", "user"]})
```

May be something like above would handle all scenarios. The path will need to be an exact match which could also become a problem, because now you might have to handle 1000s of possible paths. One option to mitigate that could be use `*`

```graphql
schema @allow(npo: {query: ["posts", "*"]})
```
The above implementation would mean that any path that starts with `posts` should be allowed. This could get complicated with usage of multiple `*` and paths before and after them.
