### ISSUE TITLE
Migrate tests that depend on jsonplaceholder from `graphql_spec` to `http_spec`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#731]
Currently there are quite a few tests in graphql_spec that connect to jsonplaceholder while executing. These tests are not only slow, they don't pass if one is offline.

**Proposal**
- Move execution tests from `graphql_spec` to `http_spec`.
- Ensure the upstream services are mocked and allows us to run tests offline.

**Technical Requirements**
- Ensure there is no drop in coverage.
- Ensure that all scenarios are 1 on 1 migrated and no edge case is missed while migrating the tests.
- Ensure tests work offline.

**Comment by guhitb** [comment]
Can I work on this?

**Comment by tusharmath** [comment]
@guhitb Sure!

**Comment by ologbonowiwi** [comment]
Putting myself on the queue in case this needs to be reassigned 🤚🏽

If you need to a hand or want to collaborate on it, let me know @guhitb 

Good luck with this collaboration! Tailcall truly amazed me since day one, and I'm sure you'll like it 🚀

**Comment by tusharmath** [comment]
Hey @guhitb, looking forward to your PR soon!

**Comment by guhitb** [comment]
Thanks @ologbonowiwi, I should have taken your offer to collaborate earlier this week. I've been struggling to figure out how the tests work. I read your pull request and think I understand things a bit better now.

**Comment by ologbonowiwi** [comment]
Hey @guhitb. I opened a PR because I thought you were not working on it
anymore.

Even though I'm familiar with tests in general and the tailcall codebase,
it was quite a challenge to migrate these as I needed to change the runner
and not only the test cases. I hope we have further opportunities to work
together in the future, and if you have any issues, concerns, or
suggestions, feel free to ping the #contributors channel on Discord or even
message me personally on Discord/e-mail/LinkedIn.

All the best to you, mate!
