### ISSUE TITLE
There shouldn't be any batching when batch.delay is set to 0

### ISSUE THREAD

**Issue by shashitnak** [tailcallhq/tailcall#737]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
When `batch: {delay: 0}` is set in the config no batching should occur.

### Steps to reproduce

1. Run the benchmarks with and without `batch: {delay: 0}` added in the config
2. Run the benchmarks with and without `batch: {delay: 1}` added in the config

### Expected behavior

There shouldn't be any difference in performance between both the benchmarks in the first step.
In the second step, the one with batching enabled should be faster.

### Actual behavior

Both `batch: {delay: 0}` and `batch: {delay: 1}` give similar performance

### Environment information:

- **Ubuntu 22.04 LTS**
- **Tailcall version v0.17.0**
- **rustc 1.74.1**
- **wrk/4.1.0-3**

**Comment by tusharmath** [comment]
@shashitnak I think a better test for this would be to see the total number of requests that are being sent. 

For example for a query such as —
```graphql
query {
  u1: user(id: 1) {name}
  u2: user(id: 2) {name}
}
```

```graphql
schema @upstream(baseURL: "http://jsonplaceholder.typicode.com", batch: {delay: 0}) {
  query: Query
}
type Query {
  user(id: Int!): User @http(path: "/users?id={{args.id}}", groupBy: ["id"]
}
```

For the above setup, two request should be made instead of one.

**Comment by adelinaenache** [comment]
Hello, new on this project. I would like to work on this! Please assign me :)

**Comment by adelinaenache** [comment]
@shashitnak @tusharmath Hey there! I've spent some time on this issue and here are the things that don't really make sense for me (first time contribution on this project, might need some guidance): 
1. By looking into `src/config/server` I can see that there is already an `batch_requests` optional boolean that resolves by default to`false` and I assume it's used to tell the server if it needs to batch the requests or not. It is also used in code but still the query gets batched, even if i set it to false in `@server`. Am I missing something here? Maybe it has another name that gets translated somewhere? Maybe it's legacy code? 

2. I am not very aware about Graphql standards, but the idea of setting the delay to 0 in order to completely turn off the batching comes as odd to me. Based on what I've read on tailcall docs I'd expect it to just have no delay between the batched requests (but that may also cause some oddities I guess). However, isn't the above mentioned parameter (`batch_requests`) a more intuitive approach to switching between batching/no batching? Or maybe `maxSize` of the batch? (we can leave it like this since I've already implemented it, haha but...still seems odd)

3.   The endpoint `http://jsonplaceholder.typicode.com/users?id=..` returns an array and the non-batched query expects an single point returned entity. I am wondering what is the expected behaviour here: Just silently take the array and convert it to a single entry (since it already has just one element) or throw some error about data not matching? What if I expect a single element but the endpoint returns instead multiple elements? (of course, this can be easily addressed in a similar fashion with  the batch-query approach, but I was just wondering which one might be the best)

**Comment by tusharmath** [comment]
> By looking into src/config/server I can see that there is already an batch_requests optional boolean that resolves by default tofalse and I assume it's used to tell the server if it needs to batch the requests or not. It is also used in code but still the query gets batched, even if i set it to false in @server. Am I missing something here? Maybe it has another name that gets translated somewhere? Maybe it's legacy code?

`batch_requests` when enabled allows for batch request at ingress. This allows a GraphQL client to send multiple graphQL requests over a single HTTP request. This setting is for the `@server` directive. The batching we are looking work with is located in `@upstream`.

> I am not very aware about Graphql standards, but the idea of setting the delay to 0 in order to completely turn off the batching comes as odd to me. Based on what I've read on tailcall docs I'd expect it to just have no delay between the batched requests (but that may also cause some oddities I guess). However, isn't the above mentioned parameter (batch_requests) a more intuitive approach to switching between batching/no batching? Or maybe maxSize of the batch? (we can leave it like this since I've already implemented it, haha but...still seems odd)

You are right, it's a bit odd. The way we are thinking about it is if the value is invalid which is any numeric value that's less than 1. It should just simply deactivate the setting. By default batching is enabled at `1ms`.


> The endpoint http://jsonplaceholder.typicode.com/users?id=.. returns an array and the non-batched query expects an single point returned entity. I am wondering what is the expected behaviour here: Just silently take the array and convert it to a single entry (since it already has just one element) or throw some error about data not matching? What if I expect a single element but the endpoint returns instead multiple elements? (of course, this can be easily addressed in a similar fashion with the batch-query approach, but I was just wondering which one might be the best)

We solve this problem by the `groupBy` operator on `@http`. The groupBy configuration, groups the list of values into a key-value pair. That's how we are able to efficiently batch and pull the data in O(1) complexity and without making n + 1 calls.

**Comment by Ashu999** [comment]
next in line, in case this needs to be reassigned

**Comment by meskill** [comment]
> You are right, it's a bit odd. The way we are thinking about it is if the value is invalid which is any numeric value that's less than 1. It should just simply deactivate the setting. By default batching is enabled at 1ms.

If the main concern of the task is to mark some values invalid for use, instead of changing the behaviour in probably unexpected way for the user it would be better to explicitly mark it as invalid. It could simply be done by replacing type of parameter to https://doc.rust-lang.org/std/num/struct.NonZeroUsize.html instead of current usize
