### ISSUE TITLE
Guide: Write a guide about Batching

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#882]
Write a guide about the batching capabilities of Tailcall. Consider a food delivery application where a lot of users are requesting the same data. Batching could be implemented based on GEO Location / City / Locality etc. Emphasize on the impact it has on performance and how it can help scale. Consider the backend to be in REST.

## Content Creation Requirements
To maintain the quality of our content, please adhere to the following guidelines:

### 1. Accuracy in Language
- **Grammar and Spelling:** Ensure your content is free from grammatical and spelling errors.

### 2. Tone and Style
- **Neutral Tone:** Maintain a neutral, non-emotional tone throughout the content.
- **Engaging Style:** Write in a free-flowing and engaging manner, keeping the reader's interest.

### 3. Content Integrity
- **Fact-Checking:** Verify all information. If unsure, use Discord to clarify.
- **Relevance:** Ensure all content is cohesive, to the point, and directly related to the title.

### 4. Originality
- **Avoid Low-Effort Content:** Content should be original and not solely generated by AI tools like ChatGPT.

**PS: Adherence to these guidelines is crucial. Content not meeting these standards may require revision or may not be accepted.**

**Comment by ibishal** [comment]
can i get assigned?

**Comment by ayewo** [comment]
Interested in working on this ✋.

**Comment by ayusham001** [comment]
@tusharmath please assign it to me

**Comment by nxshanth13** [comment]
@tusharmath brother, **I'm interested to work on this**.

**Comment by FaizanShaikh-3033** [comment]
Assign it to me, i can do it.

**Comment by tusharmath** [comment]
Have not seen any progress on this issue, unassigning it from @ayewo, let me know if someone wants to work it.

**Comment by ayusham001** [comment]
@tusharmath i would love to work on that
Please assign it to me

**Comment by ayewo** [comment]
@tusharmath was about open a PR ...

While writing this, I ran into some gaps in Tailcall's implementation of batching, and more generally, about how the `@http` operator works.

1. **We need a `jsonpath` attribute to be added to the `@http(...)` operator so it is easy to index inside JSON responses returned by upstream endpoints.**

  * 1a. The https://jsonplaceholder.typicode.com/users URL uses a top-level array for its JSON and it's response is shaped like this:
```javascript
[
  {...},
   ...,
  {...}
]
```

  * 1b. This URL https://dummyjson.com/users doesn't use a top-level array for its JSON due to its inclusion of pagination attributes so it's JSON is shaped like this:
```javascript
{
  "users": [{...}, ..., {...}],
  "total": 100,
  "skip": 0,
  "limit": 30
}
```

This difference in output is why the 2nd URL fails in Tailcall with the following error i.e.
```json
{
  "data": null,
  "errors": [
    {
      "message": "internal: expects an array",
      "locations": [
        {
          "line": 33,
          "column": 3
        }
      ],
      "path": [
        "users"
      ]
    }
  ]
}
```
Once implemented, we could use a *splat expression*[^splat] inside the `jsonpath` to target the data we need: 
```javascript
  type Query {
  users: [User]! @http(path: "/users", jsonpath: "users.[*]")
}
```

2. **Batching only supports use of keys that appear in the query params.**

  * 2a. Batching works with *query params* URLs: `https://example.com/path/users?id=1&id=4&id=7` where the query param `id` is also used for `groupBy` i.e. `@http(path: "/users", query: [{key: "id", value: "{{value.userId}}"}], groupBy: ["id"])`

  * 2b. Batching doesn't work with multiple *path params* URLs: `https://example.com/path/users/1,4,7` where the path params implies bulk fetch 3 users with the IDs `1, 4, & 7` i.e. `https://example.com/path/users/1`, `https://example.com/path/users/4`, and `https://example.com/path/users/7`). 

ipstack.com is an example of an API designed to only support multiple *path params* for [bulk requests](https://ipstack.com/documentation#bulk) requests.[^note2]


Batching on ipstack.com is done by comma-separating multiple *path params* when constructing a bulk request: 
```bash
http://api.ipstack.com/134.201.250.155,72.229.28.185,110.174.165.78
    ? access_key = ec68f1ba7cf5e70dc6cc8bca35956cf2
```

When called from a schema `@http(baseURL: "http://api.ipstack.com", path: "/{{value.ip}}", groupBy: ["ip"])`, Tailcall assumes the request is missing *query params* so it fails with the following error:
```javascript
{
  "data": null,
  "errors": [
    {
      "message": "IOException: Unable to find key ip in query params",
      "locations": [
        {
          "line": 39,
          "column": 5
        }
      ]
    }
  ]
}
```

[^splat]: [Splat expressions in HCL](https://developer.hashicorp.com/terraform/language/expressions/splat)

[^note2]: Similarly [ip-api.com](https://ip-api.com/docs/api:batch#test), [ipdata.co](https://docs.ipdata.co/docs/bulk-lookup) and [ipinfo.io](https://ipinfo.io/developers/advanced-usage#batching-requests) are 3 geolocation services whose batching endpoint will not work with Tailcall as it can only be done over POST. Tailcall only supports batching over GET requests. When I tested ip-api.com in a schema via `@http(baseURL: "http://ip-api.com", path: "/batch", method: POST, body: ...)`, the Tailcall server failed with `Error: Invalid Configuration` caused by `GroupBy is only supported for GET requests`.

**Comment by AbdoALPOP** [comment]
👋 Hey Tushar,

I am interested in your task and available to start immediately.

I am experienced with [Docusaurus.io](http://docusaurus.io/), [Nextra](https://nextra.site/), [Mkdocs](http://mkdocs.org/), and markdown. I can provide you with a user-friendly guide.

Here are some of my live guides:
- [Redstone](https://docs.redstone.finance/docs/introduction)
- [RHQ](https://documentation-orhp.vercel.app/)
- [WashMaster User Guide](https://help.dev.washmaster.ch/)

I'm looking forward to hearing from you soon 😃
[Contact me](mailto:abdoprogrammer55@gmail.com) and let's get started.

**Comment by ayewo** [comment]
.

**Comment by ayewo** [comment]
.

**Comment by ayewo** [comment]
.

**Comment by ayewo** [comment]
.

**Comment by tusharmath** [comment]
@ayewo Apologies, this has taken too long. Unfortunately, I don't think this in line with what we expected, and the to and fro on the discussion did not seem like is going anywhere. The content is too long and sort of distracts us from the main topic. I appreciate you putting time in creating this PR and hope to see more from you in the future 🙌 

Once again, sorry for not responding sooner.

**Comment by ayewo** [comment]
> @ayewo Apologies, this has taken too long. Unfortunately, I don't think this in line with what we expected, and the to and fro on the discussion did not seem like is going anywhere. The content is too long and sort of distracts us from the main topic. I appreciate you putting time in creating this PR and hope to see more from you in the future 🙌
> 
> Once again, sorry for not responding sooner.

@tusharmath well, I tried to suggest on Discord, two months ago, that Tailcall pay for the content produced so far since everything was taking to long already …

Glad you finally decided to do this but the tip is really 😏. Can you please make it $50?

Also, you’ll need to include the GitHub username for the tip command to work from here (or do it directly on the [PR](https://github.com/tailcallhq/tailcallhq.github.io/pull/97) without the username as you did above) i.e.:

```
/tip $50 @ayewo 
```
